# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Apla' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Apla
  pod 'AppCenter/Push', '~> 1.9.0'
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'



  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'React',
    :path => '../node_modules/react-native',
    :subspecs => [
      # 'Core',
      # 'RCTImage',
      # 'DevSupport'
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport'
    ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'AplaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
    end
  end
end
