# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Apla' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Apla
  pod 'AppCenter/Push', '~> 1.0.1'
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'




  target 'AplaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
